const express = require("express")
const router = express.Router()
const userSignUpController = require("../controller/user/userSignup")
const userSignInController = require("../controller/user/userSignin")
const userDetailsController = require("../controller/user/userDetails")
const authToken = require("../middleware/authToken")
const userLogout = require("../controller/user/userLogout")
const allUsers = require("../controller/user/allUsers")
const updateUser = require("../controller/user/updateUser")
const UploadProductController = require("../controller/product/uploadProduct")
const getProductController = require("../controller/product/getProduct")
const updateProductController = require("../controller/product/updateProduct")
const getCategoryProduct = require("../controller/product/getCategoryProductOne")
const getCategoryWiseProduct = require("../controller/product/getCategoryWiseProduct")
const getProductDetails = require("../controller/product/getProductDetails")
const addToCartController = require("../controller/user/addToCartController")
const countAddToCartProduct = require("../controller/user/countAddedToCartProduct")
const addToCartViewProduct = require("../controller/user/addToCartViewProduct")
const updateAddToCartProduct = require("../controller/user/updateAddToCartProduct")
const deleteAddToCartProduct = require("../controller/user/deleteAddToCartProduct")
const searchProduct = require("../controller/product/searchProduct")
const filterProductController = require("../controller/product/filterProduct")
const deleteProductController = require("../controller/product/deleteProduct")
const { addChat, getChat, getChats, readChat } = require("../controller/chat/chatController")
const { getUserByPhoneNumber } = require("../controller/user/getUserByPhoneNumber")
const { addMessage } = require("../controller/chat/messageController")
const { getNotificationNumber } = require("../controller/user/getNotification")


router.post("/signup", userSignUpController)
router.post("/signin", userSignInController)
router.get("/user-details",authToken, userDetailsController)
router.get("/userlogout", userLogout)

router.get("/all-users",authToken,allUsers)
router.post("/update-user", authToken, updateUser)

router.post("/upload-product", authToken, UploadProductController)
router.get("/get-product", getProductController)
router.post("/update-product", authToken,updateProductController)
router.post("/delete-product", authToken,deleteProductController)
router.get("/get-categoryProduct", getCategoryProduct)
router.post("/category-product", getCategoryWiseProduct)
router.post("/product-details",getProductDetails )
router.get("/search", searchProduct)
router.post("/filter-product",filterProductController)

router.post("/addtocart", authToken, addToCartController)
router.get("/countAddToCardProduct",authToken,countAddToCartProduct)
router.get("/view-cart-product",authToken,addToCartViewProduct)
router.post("/update-cart-product", authToken, updateAddToCartProduct)
router.post("/delete-cart-product", authToken, deleteAddToCartProduct)

router.get("/chats", authToken, getChats)
router.get("/chats/:id", authToken, getChat)
router.post("/chats", authToken, addChat)
router.put("/chats/read/:id", authToken, readChat)

router.post("/messages/:chatId", authToken, addMessage )

router.get("/users/phone/:phoneNumber", getUserByPhoneNumber)

router.get("/users/notification",authToken,getNotificationNumber )


module.exports = router